services:
  setalip-db:
    image: mariadb
    restart: always
    container_name: setalip-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: setalip
      MYSQL_DATABASE: setalip
      MYSQL_USER: setalip
      MYSQL_PASSWORD: setalip
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
