name: Build and Deploy

on:
  # push:
    # branches:
      # - main

  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      WHAPIFY_ACCOUNT: ${{ secrets.WHAPIFY_ACCOUNT }}
      WHAPIFY_SECRET: ${{ secrets.WHAPIFY_SECRET }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      ADMIN_URL: ${{ secrets.ADMIN_URL }}
      WEB_URL: ${{ secrets.WEB_URL }}
      TZ: ${{ secrets.TZ }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     
        

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Setup SSH port forwarding
        run: ssh -o StrictHostKeyChecking=no -L 13306:localhost:3306 -fvN ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} &

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Ensure script is executable
        run: chmod +x scripts/*

      - name: Run build script
        run: ./scripts/build.sh
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Run post-build script
        run: ./scripts/post-build.sh

      - name: Copy files using SCP
        run: |
          scp -o StrictHostKeyChecking=no ./admin.tar.gz ./web.tar.gz ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/pilates

      - name: SSH into server and run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "chmod +x /home/setalip-mono/scripts/deploy.sh && /home/setalip-mono/scripts/deploy.sh"