name: Build and Deploy

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      WHAPIFY_ACCOUNT: ${{ vars.WHAPIFY_ACCOUNT }}
      WHAPIFY_SECRET: ${{ vars.WHAPIFY_SECRET }}
      CRON_SECRET: ${{ vars.CRON_SECRET }}
      ADMIN_URL: ${{ vars.ADMIN_URL }}
      WEB_URL: ${{ vars.WEB_URL }}
      TZ: ${{ vars.TZ }}
      CLOUDFLARE_TOKEN: ${{ vars.CLOUDFLARE_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: SSH into server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -L 13306:localhost:3306 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Ensure script is executable
        run: chmod +x scripts/*

      - name: Run build script
        run: ./scripts/build.sh
      
      - name: Run post-build script
        run: ./scripts/post-build.sh

      - name: Copy files using SCP with sshpass
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} scp ./admin.tar.gz ./web.tar.gz ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/pilates

      - name: SSH into server and run deployment script
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "chmod +x /home/setalip-mono/scripts/deploy.sh && /home/setalip-mono/scripts/deploy.sh"